//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComerciantesEntities : DbContext
    {
        public ComerciantesEntities()
            : base("name=ComerciantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comerciantes> Comerciantes { get; set; }
        public virtual DbSet<Certificados> Certificados { get; set; }
        public virtual DbSet<Institucion> Institucion { get; set; }
        public virtual DbSet<Rectificaciones> Rectificaciones { get; set; }
        public virtual DbSet<Datos> Datos { get; set; }
        public virtual DbSet<Documentos> Documentos { get; set; }
        public virtual DbSet<Plantilla_Dato> Plantilla_Dato { get; set; }
        public virtual DbSet<Plantillas> Plantillas { get; set; }
        public virtual DbSet<ParametrosCC> ParametrosCC { get; set; }
        public virtual DbSet<PlantillasCC> PlantillasCC { get; set; }
        public virtual DbSet<ComerciantesRectificacionesView> ComerciantesRectificacionesView { get; set; }
        public virtual DbSet<Log_Registros> Log_Registros { get; set; }
    }
}
