//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComerciantesRectificacionesView
    {
        public int comer_id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public int Capacitacion { get; set; }
        public int insti_id { get; set; }
        public string nombre_institucion { get; set; }
        public string acronimo_institucion { get; set; }
        public int recti_id { get; set; }
        public bool rectificar_nom_ape { get; set; }
        public bool rectificar_cedula { get; set; }
        public int rectificar_inst_origen { get; set; }
        public int rectificar_inst_destino { get; set; }
        public System.DateTime fecha_rectificar { get; set; }
        public int num_solicitud { get; set; }
        public int plantillascc_id { get; set; }
        public string ruta_archivo { get; set; }
        public bool solicitud_atendida { get; set; }
    }
}
