//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int Id { get; set; }
        public System.DateTime fecha_generado { get; set; }
        public int dato_id { get; set; }
        public string ruta_archivo { get; set; }
        public string codigo_verificacion { get; set; }
        public bool valido { get; set; }
    
        public virtual Datos Datos { get; set; }
    }
}
