//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Registros
    {
        public int Id { get; set; }
        public System.DateTime fecha_log { get; set; }
        public string tipo_log { get; set; }
        public string usuario_log { get; set; }
        public string mensaje_log { get; set; }
        public string excepcion_log { get; set; }
    }
}
