//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantillas()
        {
            this.Plantilla_Dato = new HashSet<Plantilla_Dato>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public bool fecha_plantilla { get; set; }
        public bool opcional1_plantilla { get; set; }
        public bool opcional2_plantilla { get; set; }
        public bool opcional3_plantilla { get; set; }
        public bool opcional4_plantilla { get; set; }
        public string archivo_plantilla { get; set; }
        public bool plantilla_activa { get; set; }
        public bool nombres_apellidos_plantilla { get; set; }
        public bool curso_taller_plantilla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla_Dato> Plantilla_Dato { get; set; }
    }
}
