//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantillasCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlantillasCC()
        {
            this.Certificados = new HashSet<Certificados>();
            this.Rectificaciones = new HashSet<Rectificaciones>();
        }
    
        public int Id { get; set; }
        public string nombre_plantilla { get; set; }
        public System.DateTime fecha_plantilla { get; set; }
        public string archivo_plantilla { get; set; }
        public bool plantilla_activa { get; set; }
        public string documento_plantilla { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificados> Certificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rectificaciones> Rectificaciones { get; set; }
    }
}
