//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Certificados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rectificaciones
    {
        public int Id { get; set; }
        public bool rectificar_nom_ape { get; set; }
        public bool rectificar_cedula { get; set; }
        public int rectificar_inst_origen { get; set; }
        public int rectificar_inst_destino { get; set; }
        public int comerciantes_id { get; set; }
        public System.DateTime fecha_rectificar { get; set; }
        public int num_solicitud { get; set; }
        public bool solicitud_atendida { get; set; }
        public int plantillascc_id { get; set; }
        public string ruta_archivo { get; set; }
    
        public virtual Comerciantes Comerciantes { get; set; }
        public virtual PlantillasCC PlantillasCC { get; set; }
    }
}
